### PR TITLE
Simplify evidence

### LINKED ISSUE #133: Remove calls to chrome plugin as it no-longer works
Chrome no-longer supports the plugin we made to automatically do screen captures. Our sense is that due to covid, most kids know how to do screen captures, so we don't need the plugin. Can you remove the code calls that ping the plugin and produce a console error since we will no-longer need the plugin? Ideally this could go into the final app build but no real rush.

### PR DESCRIPTION
**Pull request by benloh**
Implements #141 

* The Evidence "Notes" field is now removed.
* Evidence "Idea" and "ScreenShot" are shown by default.  (And "Target" so that you can select a target).
* After selecting a target, "Rating" and "Reason" are displayed and can be edited.

Also fixes #133 
* MEME Screenshot Extension no longer tries to connect (left the code in place in case we add another extension)

### CODE REVIEW

**Comment by benloh** [comment]
@jdanish We can also hide the "TARGET NOT SET" buttons when the evidence is collapsed.  But I believe it should be visible when it's been set.   (Not implemented yet, pending your feedback)

screenshot_1382

**Comment by jdanish** [comment]
I agree thanks!

**Comment by jdanish** [comment]
Actually, I wonder if it would be easy to, when collapsed, replace the line where target not set would be with something like:

(not yet link to model)

or 

(edit to link to model)

?  

If you can add the logic I can change the text later. Otherwise this looks good to me. Thanks!

**Comment by benloh** [comment]
Message added.

**Comment by benloh** [comment]
@jdanish ready for review

**Review by jdanish — APPROVED** [review]
Looks good!

**Pull request merged**
